version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: coffeeorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
