apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
  namespace: ns-coffee-order-demo-dev
  labels:
    kubernetes.io/app: inventory-service
    kubernetes.io/component: inventory-service
spec:
  selector:
    kubernetes.io/app: inventory-service
    kubernetes.io/component: inventory-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080